{% set name = "acquifer-napari" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/acquifer-napari-{{ version }}.tar.gz
  sha256: 4a892308a3477aa5575c8acb2a89ce16095164206db7ba07e2644e79324758f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - acquifer
    - napari
    - python >={{ python_min }}

test:
  imports:
    - acquifer_napari_plugin
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/acquifer/acquifer-napari
  summary: Loader plugin for napari, to load Acquifer Imaging Machine datasets in napari, using dask for efficient lazy data-loading.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - LauLauThom
